### PR TITLE
Pull request for debug_network

### PR DESCRIPTION
**Pull request by iseong83**
Pull request to merge the debug_network branch into master. 
The big difference is the modification in `residiual_block` and the implementation of `SE-ResNet`. This branch can be run with SE-ResNet and is currently running on AWS p2.xlarge. But, I may need to double-check that it is implemented the same as the official SE-ResNet.

### CODE REVIEW

**Comment by iseong83** [comment]
The code is working without causing any issues. The original repo used `tf.map_fn` to loop views of the image. But, I changed `tf.map_fn` to my `map_images` function in `encoder.py` because the views are the second element in Tensor, not first. In `map_images`, I used a `for` loop, but I'm not sure it is a proper way to do this in Tensorflow. If I can, I want to avoid to use `get_shape()` function. Could you take a look at this? Thanks.

**Comment by zhampel** [comment]
Help me out by quoting the line number ranges you want me to look at.

**Comment by iseong83** [comment]
It's the line 7-13 in `encoder.py` [link](https://github.com/iseong83/3d_object_reconstruction/blob/ed0be78ae60d95cc25879a5a8c3a638513fc9871/Reco3D/lib/encoder.py#L7-L13)

**Comment by zhampel** [comment]
Ok thanks. What's your motivation to not use the `get_shape()` function?

**Comment by iseong83** [comment]
Ultimately, I want to remove the preprocess function L49-50 in `network.py` ([link](https://github.com/iseong83/3d_object_reconstruction/blob/ed0be78ae60d95cc25879a5a8c3a638513fc9871/Reco3D/lib/network.py#L49-L50)) because I want to vary the number of views in the testing stage. The preprocess function (L49-50 ) in `network.py` prevents this. If I remove this, then `get_shape()` causes an error. I think it's because dimensions are not defined if I removed L49-50.

**Comment by zhampel** [comment]
Hmmm, I'm not sure exactly how to approach this. I'm confused: shouldn't most of these layers just do the operation correctly on the full tensor? Or perhaps is it possible to reshape/view in a way that doesn't require the `get_shape()` function and instead reorders the tensor indices in the way these layers should expect them?

**Comment by iseong83** [comment]
Yes, just a couple of hours ago, I actually came to the same idea that reordering the tensor indices. I will try to implement it tonight. Thank you for your advice!

**Comment by zhampel** [comment]
Does the `tf.transpose()` solve your index ordering issue??!!

**Comment by iseong83** [comment]
Yes, I think so. The shape of the tensor was correct. I added it [here](https://github.com/iseong83/3d_object_reconstruction/blob/6eb81354de138415ad3a372c04ac3448f639f2b4/Reco3D/lib/network.py#L55-L69) in `network.py` which is before calling `encoder.py`. So, this way I can use `tf.map_fn`. If you have any concerns, please let me know.

**Comment by zhampel** [comment]
I've approved for now, so you can move forward with the next steps. You can merge when ready and then cut a new branch for the next set of features you'll be adding. I highly recommend adding more comments as your codebase finalizes as well. They are a bit too sparse for ease of viewing.

**Comment by iseong83** [comment]
Thank you. I will add more comments to make it more clear.

**Pull request merged**
