### PR TITLE
Merging dev_feature1 branch

### PR DESCRIPTION
**Pull request by iseong83**
I implemented the re-training module and [weighted softmax loss function](https://github.com/iseong83/3d_object_reconstruction/blob/38c0494f3327a25a074acbdf8e9bb2efc4292a49/Reco3D/lib/loss.py#L21-L35). I think the fine-tuning class ([line](https://github.com/iseong83/3d_object_reconstruction/blob/38c0494f3327a25a074acbdf8e9bb2efc4292a49/Reco3D/lib/network.py#L378)) is not designed well. So, this part needs more improvements. I don't have a particular review request for this branch.

### CODE REVIEW

**Comment by iseong83** [comment]
I also updated Readme for the description and added setup.py for the installation. I tested setup.py in AWS. @zhampel Could you review my Readme and setup.py? Thank you.

**Comment by zhampel** [comment]
So I got the saved, frozen model params as you show. However, when I run the first inference, I get the following error:

```
$ python tests/inference_3d.py
Traceback (most recent call last):
  File "tests/inference_3d.py", line 4, in <module>
    tf.compat.v1.disable_v2_behavior()
AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'
```

The error disappears by commenting out the 4th line, but be aware that this could cause issues to others. Recall that I've run through your installation and environment setup steps...

I also recommend that you show some examples, like the inference chairs, on your README. That does more explaining than words can do!

**Comment by iseong83** [comment]
Thank you @zhampel. I will implement all your suggestions tonight. I will also put the`model.tar` in AWS S3. So, anyone can access it. I will let you know when it's done.

**Comment by iseong83** [comment]
I have implemented all your suggestions and removed the 4th line in `inference_3d.py`. I also add a link for my Streamlit [demo](http://34.210.191.147:8501/) in README. Please take a look and let me know if you have further suggestions.

**Comment by iseong83** [comment]
Hi, Zig. I removed the link to the Streamlit app in README because it's running on AWS. I'm worried about any possible security issues. Instead, I put the link to my slide deck.

**Comment by zhampel** [comment]
@iseong83 sounds good. Maybe check with the AI leads/Streamlit team to see if there are any possible security issues. Perhaps it's ok to leave it on the README as well.

**Comment by iseong83** [comment]
Thanks, I will check with the AI leads/Streamlit team. Do you think it's okay to merge into `master`? or do you want to double-check this?

**Pull request merged**
